# Exemples de fonctions Pandas utiles pour le TP 1

## Importations des librairies utiles

In [1]:
import numpy as np
import pandas as pd

print('numpy %s, pandas %s'%(np.__version__,pd.__version__))

numpy 1.26.4, pandas 2.2.2


## Creation depuis un CSV et affichage d'un Dataframe Pandas

In [6]:
my_dataframe = pd.read_csv('/iris.csv', dtype={'id_Iris': int})
my_dataframe

id_Iris  Longueur Sépale (cm)  Largeur Sépale (cm)  Longueur Pétale (cm)  \
0         23                   NaN                  NaN                   1.4   
1        104                   4.9                  3.0                   1.4   
2         18                   4.7                  3.2                   1.3   
3         49                   4.6                  3.1                   1.5   
4        123                   5.0                  3.6                   1.4   
..       ...                   ...                  ...                   ...   
145      124                   6.7                  3.0                   5.2   
146       44                   6.3                  2.5                   5.0   
147       69                   6.5                  3.0                   NaN   
148       56                   6.2                  3.4                   5.4   
149        5                   5.9                  3.0                   5.1   

     Largeur Pétale (cm)  Type Iris  
0                    0.2          0  
1                    0.2          0  
2                    0.2          0  
3                    0.2          0  
4                    0.2          0  
..                   ...        ...  
145                  2.3          2  
146                  1.9          2  
147                  2.0          2  
148                  2.3          2  
149                  1.8          2  

[150 rows x 6 columns]

### Quelques Affichages du dataframe

In [7]:
my_dataframe.sample(5) # Affiche 5 lignes aléatoires

id_Iris  Longueur Sépale (cm)  Largeur Sépale (cm)  Longueur Pétale (cm)  \
133       75                   6.3                  2.8                   5.1   
48         1                   5.3                  3.7                   1.5   
126       82                   6.2                  2.8                   4.8   
120      111                   6.9                  3.2                   5.7   
52        33                   NaN                  3.1                   4.9   

     Largeur Pétale (cm)  Type Iris  
133                  1.5          2  
48                   0.2          0  
126                  1.8          2  
120                  2.3          2  
52                   1.5          1

In [8]:
my_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   id_Iris               150 non-null    int64  
 1   Longueur Sépale (cm)  142 non-null    float64
 2   Largeur Sépale (cm)   142 non-null    float64
 3   Longueur Pétale (cm)  143 non-null    float64
 4   Largeur Pétale (cm)   146 non-null    float64
 5   Type Iris             150 non-null    int64  
dtypes: float64(4), int64(2)
memory usage: 7.2 KB


In [9]:
my_dataframe.mean()

id_Iris                 74.500000
Longueur Sépale (cm)     5.846479
Largeur Sépale (cm)      3.049296
Longueur Pétale (cm)     3.756643
Largeur Pétale (cm)      1.208219
Type Iris                1.000000
dtype: float64

In [10]:
my_dataframe.dtypes # provides information about the data type of each column in the DataFrame

id_Iris                   int64
Longueur Sépale (cm)    float64
Largeur Sépale (cm)     float64
Longueur Pétale (cm)    float64
Largeur Pétale (cm)     float64
Type Iris                 int64
dtype: object

## Transformation d'une colonne en index

In [11]:
my_dataframe.set_index('id_Iris',inplace=True)
my_dataframe

Longueur Sépale (cm)  Largeur Sépale (cm)  Longueur Pétale (cm)  \
id_Iris                                                                    
23                        NaN                  NaN                   1.4   
104                       4.9                  3.0                   1.4   
18                        4.7                  3.2                   1.3   
49                        4.6                  3.1                   1.5   
123                       5.0                  3.6                   1.4   
...                       ...                  ...                   ...   
124                       6.7                  3.0                   5.2   
44                        6.3                  2.5                   5.0   
69                        6.5                  3.0                   NaN   
56                        6.2                  3.4                   5.4   
5                         5.9                  3.0                   5.1   

         Largeur Pétale (cm)  Type Iris  
id_Iris                                  
23                       0.2          0  
104                      0.2          0  
18                       0.2          0  
49                       0.2          0  
123                      0.2          0  
...                      ...        ...  
124                      2.3          2  
44                       1.9          2  
69                       2.0          2  
56                       2.3          2  
5                        1.8          2  

[150 rows x 5 columns]

## Tri selon l'index

In [12]:
my_dataframe.sort_index(inplace=True) # Inplace permet de conserver les modifications du DataFrame
my_dataframe

Longueur Sépale (cm)  Largeur Sépale (cm)  Longueur Pétale (cm)  \
id_Iris                                                                    
0                         4.9                  3.1                   1.5   
1                         5.3                  3.7                   1.5   
2                         6.7                  3.1                   4.4   
3                         5.0                  3.0                   1.6   
4                         5.7                  NaN                   4.2   
...                       ...                  ...                   ...   
145                       6.5                  2.8                   4.6   
146                       6.0                  2.2                   4.0   
147                       4.6                  3.4                   1.4   
148                       7.3                  2.9                   NaN   
149                       6.8                  3.2                   5.9   

         Largeur Pétale (cm)  Type Iris  
id_Iris                                  
0                        0.2          0  
1                        0.2          0  
2                        1.4          1  
3                        0.2          0  
4                        1.3          1  
...                      ...        ...  
145                      1.5          1  
146                      1.0          1  
147                      0.3          0  
148                      1.8          2  
149                      2.3          2  

[150 rows x 5 columns]

## Sélection d'une colonne de Dataframe

In [13]:
my_dataframe['Largeur Sépale (cm)']

id_Iris
0      3.1
1      3.7
2      3.1
3      3.0
4      NaN
      ... 
145    2.8
146    2.2
147    3.4
148    2.9
149    3.2
Name: Largeur Sépale (cm), Length: 150, dtype: float64

## Sélection d'une sous-partie de Dataframe (Slice) avec loc

In [14]:
my_dataframe.loc[124:128,'Largeur Sépale (cm)':'Largeur Pétale (cm)']

Largeur Sépale (cm)  Longueur Pétale (cm)  Largeur Pétale (cm)
id_Iris                                                                
124                      3.0                   5.2                  2.3
125                      3.5                   NaN                  0.3
126                      2.7                   5.3                  1.9
127                      3.1                   1.6                  0.2
128                      2.3                   4.4                  1.3

In [15]:
mon_petit_dataframe = my_dataframe.loc[145:,['Longueur Sépale (cm)','Longueur Pétale (cm)','Type Iris']]
mon_petit_dataframe

Longueur Sépale (cm)  Longueur Pétale (cm)  Type Iris
id_Iris                                                       
145                       6.5                   4.6          1
146                       6.0                   4.0          1
147                       4.6                   1.4          0
148                       7.3                   NaN          2
149                       6.8                   5.9          2

## Filtre

In [16]:
display(mon_petit_dataframe['Longueur Pétale (cm)']>4)
mon_petit_dataframe[mon_petit_dataframe['Longueur Pétale (cm)']>4]

id_Iris
145     True
146    False
147    False
148    False
149     True
Name: Longueur Pétale (cm), dtype: bool

Longueur Sépale (cm)  Longueur Pétale (cm)  Type Iris
id_Iris                                                       
145                       6.5                   4.6          1
149                       6.8                   5.9          2

## Modification en masse (Vectorisation)

In [17]:
mon_petit_dataframe * 2

Longueur Sépale (cm)  Longueur Pétale (cm)  Type Iris
id_Iris                                                       
145                      13.0                   9.2          2
146                      12.0                   8.0          2
147                       9.2                   2.8          0
148                      14.6                   NaN          4
149                      13.6                  11.8          4

In [18]:
mon_petit_dataframe['Longueur Pétale (cm)'] = mon_petit_dataframe['Longueur Pétale (cm)'] -1
mon_petit_dataframe

Longueur Sépale (cm)  Longueur Pétale (cm)  Type Iris
id_Iris                                                       
145                       6.5                   3.6          1
146                       6.0                   3.0          1
147                       4.6                   0.4          0
148                       7.3                   NaN          2
149                       6.8                   4.9          2

## Agrégation avec Groupby

In [19]:
my_dataframe.groupby("Type Iris")["Largeur Pétale (cm)"].mean()

Type Iris
0    0.245833
1    1.328571
2    2.030612
Name: Largeur Pétale (cm), dtype: float64

## Conversion en Numpy

In [20]:
my_array=mon_petit_dataframe.values
print(type(my_array))
my_array

<class 'numpy.ndarray'>


array([[6.5, 3.6, 1. ],
       [6. , 3. , 1. ],
       [4.6, 0.4, 0. ],
       [7.3, nan, 2. ],
       [6.8, 4.9, 2. ]])

## Quelques opérations NumPy

In [21]:
my_array[3,2]

2.0

In [22]:
my_array[-1,1]

4.9

In [23]:
my_array + 1

array([[7.5, 4.6, 2. ],
       [7. , 4. , 2. ],
       [5.6, 1.4, 1. ],
       [8.3, nan, 3. ],
       [7.8, 5.9, 3. ]])

In [24]:
my_array + np.array([1,2,3])

array([[7.5, 5.6, 4. ],
       [7. , 5. , 4. ],
       [5.6, 2.4, 3. ],
       [8.3, nan, 5. ],
       [7.8, 6.9, 5. ]])

In [25]:
my_array == 1

array([[False, False,  True],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [26]:
np.isnan(my_array)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False],
       [False, False, False]])

In [27]:
my_array[np.isnan(my_array)]=0
my_array

array([[6.5, 3.6, 1. ],
       [6. , 3. , 1. ],
       [4.6, 0.4, 0. ],
       [7.3, 0. , 2. ],
       [6.8, 4.9, 2. ]])

In [28]:
my_array.reshape(3, 5)

array([[6.5, 3.6, 1. , 6. , 3. ],
       [1. , 4.6, 0.4, 0. , 7.3],
       [0. , 2. , 6.8, 4.9, 2. ]])

In [29]:
my_doublearray = np.concatenate([my_array,my_array])
display(my_doublearray)
my_doublearray.shape

array([[6.5, 3.6, 1. ],
       [6. , 3. , 1. ],
       [4.6, 0.4, 0. ],
       [7.3, 0. , 2. ],
       [6.8, 4.9, 2. ],
       [6.5, 3.6, 1. ],
       [6. , 3. , 1. ],
       [4.6, 0.4, 0. ],
       [7.3, 0. , 2. ],
       [6.8, 4.9, 2. ]])

(10, 3)

In [30]:
my_doublearray.reshape(3, 5, 2)

array([[[6.5, 3.6],
        [1. , 6. ],
        [3. , 1. ],
        [4.6, 0.4],
        [0. , 7.3]],

       [[0. , 2. ],
        [6.8, 4.9],
        [2. , 6.5],
        [3.6, 1. ],
        [6. , 3. ]],

       [[1. , 4.6],
        [0.4, 0. ],
        [7.3, 0. ],
        [2. , 6.8],
        [4.9, 2. ]]])